language: php
php:
  - 7.2

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

install:
  - rm composer.lock
  - composer update --no-scripts
  - cp .env.testing .env
  - php artisan clear-compiled
  - php artisan env
  - wget -q https://github.com/firefly-iii/test-data/raw/master/storage/database.sqlite -O storage/database/database.sqlite
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit -c phpunit.coverage.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -x storage/build/clover-all.xml

# safelist
branches:
  only:
  - develop
  - master
