language: php

php:
  - 5.5
  - 5.6

addons:
  code_climate:
    repo_token: 26489f9e854fcdf7e7660ba29c1455694685465b1f90329a79f7d2bf448acb61

install:
  - rm composer.lock
  - composer install
  - php artisan env
  - mv -v .env.testing .env

script:
  - ./tests/_data/db.sh
  - php vendor/bin/codecept build
  - php vendor/bin/codecept run --coverage --coverage-xml --debug

after_script:
  - cp -v tests/_output/coverage.xml build/logs/clover.xml
  - php vendor/bin/coveralls
  - vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"