language: php
php:
  - '7.4'
dist: xenial
os: linux

cache:
  directories:
    - /home/travis/.config
    - /home/travis/build/firefly-iii/firefly-iii/vendor

branches:
  only:
    - develop

before_script:
  - phpenv config-rm xdebug.ini || return 0

script:
  - ./.ci/phpstan.sh