---
name: Issues - Reply to closed issue
on:
  issues:
    types:
      - closed
jobs:
  command_and_close:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/closed-issue-message@v2
        with:
          message: |
            Hi there! This is an automatic reply. `Share and enjoy`

            This issue is now ðŸ”’ closed. Please be aware that closed issues are not monitored by the developer of Firefly III.

            - If the original bug is not actually fixed, please open [a new issue](https://github.com/firefly-iii/firefly-iii/issues/new/choose). Refer to this issue for clarity.
            - Follow-up questions must be posted in a new [discussion](https://github.com/firefly-iii/firefly-iii/discussions/)
            - Further replies to this issue may get no response.

            If there is more to discuss, please open [a new issue](https://github.com/firefly-iii/firefly-iii/issues/new/choose) or [discussion](https://github.com/firefly-iii/firefly-iii/discussions/).

            Thank you for your contributions.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
