name: "Issues - Command to close duplicate issues"

# the workflow to execute on is comments that are newly created
on:
  issue_comment:
    types: [ created ]

permissions:
  issues: write
  checks: read

jobs:
  close_duplicates:
    runs-on: ubuntu-latest
    steps:
      - uses: github/command@v1.2.2
        id: command
        with:
          allowed_contexts: "issue"
          command: ".duplicate"
      - name: reply
        if: ${{ steps.command.outputs.continue == 'true' }}
        run: |

          ISSUE_TITLE=$(gh issue view ${{ steps.command.outputs.params }} --json title --jq '.title')

          gh issue comment "$NUMBER" --body "Hi there!

          This is an automatic reply. \`Share and enjoy\`.

          Your issue is probably a duplicate of issue <span>#</span>${{ steps.command.outputs.params }}: [$ISSUE_TITLE](https://github.com/firefly-iii/firefly-iii/issues/${{ steps.command.outputs.params }}). Please refer to issue #${{ steps.command.outputs.params }} for support.

          You can close this issue now. If you believe this is not in fact a duplicate, please reply and let us know. Otherwise, this issue will be automatically closed in a few days time.

          Thank you for your contributions."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
